### ISSUE TITLE
im gonna fuck your mother harder than life is fucking you <333

### ISSUE THREAD

**Issue by dylanjamesdev** [LunarsDev/AGB-Source#3]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaa

**Comment by dylanjamesdev** [comment]
@LunarsDev/site @LunarsDev/software @LunarsDev/fateslist @LunarsDev/lunar-site <33333

**Comment by Motzumoto** [comment]
dude get a life
